version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pg_chat_bot
    environment:
      POSTGRES_DB: chat_bot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
    driver: bridge
